# Generated by Django 5.2.8 on 2025-11-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('Student', 'Student'), ('Opiekun Praktyk', 'Opiekun Praktyk'), ('Pracownik BK', 'Pracownik BK'), ('Pracodawca', 'Pracodawca')], max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('status_konta', models.BooleanField(null=True)),
                ('numer_telefonu', models.CharField(max_length=15, null=True)),
                ('adres_mailowy', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaliczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField(null=True)),
                ('data_zakonczenia', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=100, null=True)),
                ('numer_budynku', models.CharField(max_length=10)),
                ('numer_lokalu', models.CharField(max_length=10, null=True)),
                ('kod_pocztowy', models.CharField(max_length=10)),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjaTest.kraj')),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjaTest.miasto')),
            ],
        ),
        migrations.CreateModel(
            name='Pracodawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_przedstawiciela', models.CharField(max_length=50, null=True)),
                ('nazwisko_przedstawiciela', models.CharField(max_length=50, null=True)),
                ('nazwa_firmy', models.CharField(max_length=100, null=True)),
                ('nip', models.CharField(max_length=10, null=True)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjaTest.adres')),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(null=True)),
                ('rodzaj_zgloszenia', models.CharField(choices=[('Praca zawodowa', 'Praca zawodowa'), ('Praktyki', 'Praktyki'), ('Staż', 'Staż'), ('JDG', 'JDG')], max_length=30)),
                ('dostepnosc_oferty', models.CharField(choices=[('Publiczna', 'Publiczna'), ('Niepubliczna', 'Niepubliczna')], max_length=20)),
                ('pracodawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.pracodawca')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('numer_indeksu', models.CharField(max_length=20, unique=True)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjaTest.adres')),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='PracownikBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, null=True)),
                ('nazwisko', models.CharField(max_length=50, null=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='OpiekunPraktyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, null=True)),
                ('nazwisko', models.CharField(max_length=50, null=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wpisu', models.DateTimeField(null=True)),
                ('dzien_praktyk', models.DateTimeField(null=True)),
                ('szczegoly', models.TextField(null=True)),
                ('zaliczenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.zaliczenie')),
            ],
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Zgłoszone', 'Zgłoszone'), ('Zaakceptowane', 'Zaakceptowane'), ('Odrzucone', 'Odrzucone'), ('Zaliczone', 'Zaliczone'), ('Niezaliczone', 'Niezaliczone')], max_length=20, null=True)),
                ('ocena_dla_pracodawcy', models.IntegerField(null=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.oferta')),
                ('opiekun_praktyk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacjaTest.opiekunpraktyk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.student')),
            ],
        ),
        migrations.AddField(
            model_name='zaliczenie',
            name='zgloszenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.zgloszenie'),
        ),
        migrations.CreateModel(
            name='Zalacznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.CharField(max_length=500, null=True)),
                ('data_dodania', models.DateTimeField(null=True)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.zgloszenie')),
            ],
        ),
        migrations.CreateModel(
            name='OcenaDlaPracodawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(null=True)),
                ('komentarz', models.TextField(null=True)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaTest.zgloszenie')),
            ],
        ),
    ]
