# Generated by Django 5.2.8 on 2025-12-02 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaTest', '0002_load_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='opiekun_praktyk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacjaTest.opiekunpraktyk'),
        ),
    ]
