# Generated by Django 4.2.27 on 2025-12-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaTest', '0002_alter_testpraktyki_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpraktyki',
            options={'permissions': [('add_offer_portal', 'Może dodawać ofertę w portalu'), ('change_offer_portal', 'Może edytować ofertę w portalu'), ('delete_offer_portal', 'Może usuwać ofertę z portalu'), ('view_own_applications', 'Może widzieć własne zgłoszenia'), ('view_assigned_applications', 'Może widzieć przypisane zgłoszenia'), ('view_students', 'Może widzieć listę studentów'), ('view_tutors', 'Może widzieć listę opiekunów'), ('view_employers', 'Może widzieć listę pracodawców'), ('view_users', 'Może widzieć listę użytkowników'), ('view_user_profile', 'Może widzieć profil użytkownika'), ('change_user_profile', 'Może edytować profil użytkownika'), ('change_user_status', 'Może zmieniać status konta użytkownika')]},
        ),
    ]
