# Generated by Django 4.2.27 on 2025-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaTest', '0003_alter_zgloszenie_opiekun_praktyk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPRaktyki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('add_offer_portal', 'Może dodawać ofertę w portalu'), ('view_own_applications', 'Może widzieć własne zgłoszenia'), ('view_assigned_applications', 'Może widzieć przypisane zgłoszenia'), ('view_students', 'Może widzieć listę studentów'), ('view_tutors', 'Może widzieć listę opiekunów'), ('view_employers', 'Może widzieć listę pracodawców')],
            },
        ),
    ]
